// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlmiSwZYnUNvSgxTuEWBbMrCm56cM9voc',
    appId: '1:909961869598:web:490b9e3269ee005ceff10f',
    messagingSenderId: '909961869598',
    projectId: 'prueba-codigomanu',
    authDomain: 'prueba-codigomanu.firebaseapp.com',
    storageBucket: 'prueba-codigomanu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Gzw_orkhQebvkcYG5a7xBiUmfNUrfw4',
    appId: '1:909961869598:android:ebbeec16fb5f2954eff10f',
    messagingSenderId: '909961869598',
    projectId: 'prueba-codigomanu',
    storageBucket: 'prueba-codigomanu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2L5m5-um1RXwyxwlPrb3RilqX-XjeCU',
    appId: '1:909961869598:ios:dec4a067a7f3d55eeff10f',
    messagingSenderId: '909961869598',
    projectId: 'prueba-codigomanu',
    storageBucket: 'prueba-codigomanu.appspot.com',
    iosClientId: '909961869598-tvgab4huatore696s7cca89kqlc2f2u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2L5m5-um1RXwyxwlPrb3RilqX-XjeCU',
    appId: '1:909961869598:ios:dec4a067a7f3d55eeff10f',
    messagingSenderId: '909961869598',
    projectId: 'prueba-codigomanu',
    storageBucket: 'prueba-codigomanu.appspot.com',
    iosClientId: '909961869598-tvgab4huatore696s7cca89kqlc2f2u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );
}
